network:
  version: 2
  renderer: networkd
  ethernets:
    vlan_staff:
      match:
        macaddress: "08:00:78:DB:00:16"
      set-name: vlan_staff
      dhcp4: false
      addresses: [ "172.28.5.10/24" ]
      routes:
        - to: default
          via: 172.28.5.254
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]




