network:
  version: 2
  renderer: networkd
  ethernets:
    vlan_compta:
      match:
        macaddress: "08:00:78:CC:00:11"
      set-name: vlan_compta
      dhcp4: false
      addresses: [ "172.28.3.10/24" ]
      routes:
        - to: default
          via: 172.28.3.254
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]




